load("exec_test.bzl", "exec_test")

exec_test(
    name = "simple-no-deps-bin",
    bin = "//example-projects/simple-no-deps-bin:simple-no-deps-bin"
)


exec_test(
    name = "simple-single-dep-bin",
    bin = "//example-projects/simple-single-dep-bin:simple-single-dep-bin"
)


exec_test(
    name = "bin-with-build-rs",
    bin = "//example-projects/bin-with-build-rs:bin-with-build-rs"
)

exec_test(
    name = "proc-macro-dep",
    bin = "//example-projects/proc-macro-dep:proc-macro-dep"
)

exec_test(
    name = "renamed-dep",
    bin = "//example-projects/renamed-dep:renamed-dep"
)
