load(
    "@prelude//rust:cargo_buildscript.bzl",
    "buildscript_run",
)

rust_binary(
    name = "simple-no-deps-bin",
    visibility = ["PUBLIC"],
    srcs = glob(["src/*.rs"]),
    edition = "2024",
    deps = [],
    crate_root = "src/main.rs",
    crate = "simple-no-deps-bin",
    features = [],
    env = {
        "CARGO_PKG_VERSION": "0.1.0",
        "CARGO_PKG_VERSION_PATCH": "0",
    },
)

