rust_binary(
    name = "simple-no-deps-bin",
    visibility = ["PUBLIC"],
    srcs = glob(["src/*.rs"]),
    edition = "2024",
    deps = [],
    crate_root = "src/main.rs",
    crate = "simple-no-deps-bin",
)

